{{- if .Values.consoleEmbed.enabled }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: console-embed
  namespace: openshift-console
spec:
  host: console-embed-openshift-console.{{ .Values.deployer.domain }}
  port:
    targetPort: https
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: reencrypt
  to:
    kind: Service
    name: console
    weight: 100
  wildcardPolicy: None
  httpHeaders:
    actions:
      response:
      - name: X-Frame-Options
        action:
          type: Delete
      - name: Content-Security-Policy
        action:
          type: Delete
      - name: Content-Security-Policy-Report-Only
        action:
          type: Delete
{{- end }}
