{{- if .Values.consoleEmbed.enabled }}
---
apiVersion: operator.openshift.io/v1
kind: Console
metadata:
  name: cluster
spec:
  unsupportedConfigOverrides:
    contentSecurityPolicyEnabled: false
{{- end }}
