{{- if .Values.users.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: workshop-users-htpasswd
  namespace: openshift-config
  labels:
    demo.redhat.com/application: "field-content"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  htpasswd: |
    {{- $passwordHash := "$2y$05$Npky/ODk0FKTIojJub5T2ePBFV2yh7RygzPJVP6nDQM1eHbITHZUi" }}
    {{- if .Values.users.admin.enabled }}
    {{ .Values.users.admin.username }}:{{ $passwordHash }}
    {{- end }}
    {{- range $i := until (int .Values.users.count) }}
    {{- $username := printf "%s%d" $.Values.users.prefix (add1 $i) }}
    {{ $username }}:{{ $passwordHash }}
    {{- end }}
{{- end }}
