{{- if and .Values.users.enabled .Values.users.manageOAuth }}
---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
  labels:
    demo.redhat.com/application: "field-content"
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: "ServerSideApply=true"
spec:
  identityProviders:
  - name: workshop-users-htpasswd
    mappingMethod: claim
    type: HTPasswd
    htpasswd:
      fileData:
        name: workshop-users-htpasswd
{{- end }}
